# Generated by Django 6.0.5 on 2026-06-17 21:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='likes',
        ),
        migrations.AddField(
            model_name='meme',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_memes', to=settings.AUTH_USER_MODEL),
        ),
    ]
